# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 771, 661))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tmsTree = QtWidgets.QTreeView(self.verticalLayoutWidget_2)
        self.tmsTree.setObjectName("tmsTree")
        self.horizontalLayout.addWidget(self.tmsTree)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_tl = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_tl.setObjectName("radioButton_tl")
        self.verticalLayout.addWidget(self.radioButton_tl)
        self.radioButton_tms = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_tms.setObjectName("radioButton_tms")
        self.verticalLayout.addWidget(self.radioButton_tms)
        self.importButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.importButton.setObjectName("importButton")
        self.verticalLayout.addWidget(self.importButton)
        self.pullButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pullButton.setObjectName("pullButton")
        self.verticalLayout.addWidget(self.pullButton)
        self.exportButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.myTree = QtWidgets.QTreeView(self.verticalLayoutWidget_2)
        self.myTree.setObjectName("myTree")
        self.horizontalLayout.addWidget(self.myTree)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.caseView = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.caseView.setObjectName("caseView")
        self.horizontalLayout_2.addWidget(self.caseView)
        self.contentList = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.contentList.setObjectName("contentList")
        self.horizontalLayout_2.addWidget(self.contentList)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_tl.setText(_translate("MainWindow", "From TestLink"))
        self.radioButton_tms.setText(_translate("MainWindow", "From TMS"))
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.pullButton.setText(_translate("MainWindow", ">>"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
